# Generated by Django 5.0 on 2023-12-14 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="publisher",
            table="publisher",
        ),
    ]
