# Generated by Django 5.0 on 2023-12-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_book_contributor_alter_publisher_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="reviews.publisher",
            ),
        ),
        migrations.CreateModel(
            name="BookContributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("AUTHOR", "Author"),
                            ("CO_AUTHOR", "Co-Author"),
                            ("EDITOR", "Editor"),
                        ],
                        max_length=20,
                        verbose_name="The role this contributor had in the book.",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reviews.book"
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.contributor",
                    ),
                ),
            ],
            options={
                "db_table": "book_contributors",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="contributors",
            field=models.ManyToManyField(
                through="reviews.BookContributor", to="reviews.contributor"
            ),
        ),
    ]
